POST http://localhost:8000/products
content-type: application/json

{
    "name": "Caderno 10 matérias",
    "price": 20
}

###

GET http://localhost:8000/products

###

GET http://localhost:8000/products/145e5c7e-396c-431b-86bc-841deae6d39b

###
PUT http://localhost:8000/products/ff130cc9-8162-4100-a5b3-4dae5bc42da3
content-type: application/json

{
    "name": "Caderno 10 matérias preto",
    "price": 22.50
}

###

DELETE http://localhost:8000/products/ff130cc9-8162-4100-a5b3-4dae5bc42da3